//! Byte/behavior-parity tests for the Phase-2 event engine and state resolution.
//!
//! Expected values in `fixtures/phase2.json` are the actual output of strix's
//! `events.ts` / `state-resolution.ts` (generated by `fixtures/gen-phase2.mjs`).
//! Loaded at runtime so this file compiles even before the fixture exists; the
//! tests fail loudly (file missing) until it is generated.

use std::collections::HashMap;
use std::fs;

use scandiaca::events::{build_event, check_event_auth, select_auth_events, BuildEventParams};
use scandiaca::signing::{import_signing_key, SigningKey};
use scandiaca::state_resolution::resolve_state;
use scandiaca::types::internal::{RoomState, StateEvents};
use serde_json::Value;

fn load() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/phase2.json");
    let s = fs::read_to_string(path).expect("tests/fixtures/phase2.json must exist");
    serde_json::from_str(&s).expect("phase2.json must be valid JSON")
}

fn test_key() -> SigningKey {
    import_signing_key("ed25519:test", [1u8; 32])
}

fn state_events_from(obj: &Value) -> StateEvents {
    obj.as_object()
        .expect("state map must be an object")
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect()
}

fn room_from(v: &Value) -> RoomState {
    RoomState {
        room_id: v["room_id"].as_str().unwrap_or("").into(),
        room_version: v["room_version"].as_str().unwrap_or("").to_string(),
        state_events: state_events_from(&v["state_events"]),
        depth: v["depth"].as_i64().unwrap_or(0),
        forward_extremities: v["forward_extremities"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(Into::into))
                    .collect()
            })
            .unwrap_or_default(),
        state_event_ids: std::collections::BTreeMap::new(),
    }
}

fn str_vec(v: &Value) -> Vec<String> {
    v.as_array()
        .map(|a| {
            a.iter()
                .filter_map(|x| x.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default()
}

#[test]
fn build_event_parity() {
    let d = load();
    let key = test_key();
    for case in d["buildEvent"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap_or("?");
        let p = &case["params"];
        let content = p["content"].clone();
        let prev_events = str_vec(&p["prevEvents"]);
        let auth_events = str_vec(&p["authEvents"]);
        let signed = p.get("signed").and_then(Value::as_bool).unwrap_or(false);

        let params = BuildEventParams {
            room_id: p["roomId"].as_str().unwrap_or(""),
            sender: p["sender"].as_str().unwrap_or(""),
            event_type: p["type"].as_str().unwrap_or(""),
            content,
            state_key: p.get("stateKey").and_then(Value::as_str),
            depth: p["depth"].as_i64().unwrap_or(0),
            prev_events,
            auth_events,
            redacts: p.get("redacts").and_then(Value::as_str),
            unsigned: p.get("unsigned").cloned(),
            server_name: p["serverName"].as_str().unwrap_or("test.localhost"),
            signing_key: if signed { Some(&key) } else { None },
            room_version: p.get("roomVersion").and_then(Value::as_str),
            origin_server_ts: p.get("originServerTs").and_then(Value::as_i64),
        };

        let (event, event_id) = build_event(params);
        assert_eq!(
            event_id,
            case["eventId"].as_str().unwrap(),
            "eventId mismatch [{label}]"
        );
        assert_eq!(event, case["event"], "event mismatch [{label}]");
    }
}

#[test]
fn select_auth_events_parity() {
    let d = load();
    for case in d["selectAuthEvents"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap_or("?");
        let room = room_from(&case["roomState"]);
        let content = case.get("content").and_then(Value::as_object);
        let got = select_auth_events(
            case["eventType"].as_str().unwrap(),
            case.get("stateKey").and_then(Value::as_str),
            &room,
            case["sender"].as_str().unwrap(),
            content,
        );
        assert_eq!(
            got,
            str_vec(&case["authEvents"]),
            "authEvents mismatch [{label}]"
        );
    }
}

#[test]
fn check_event_auth_parity() {
    let d = load();
    for case in d["checkEventAuth"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap_or("?");
        let room = room_from(&case["roomState"]);
        let result = check_event_auth(&case["event"], &room);
        let exp = &case["result"];
        if exp["ok"].as_bool() == Some(true) {
            assert!(
                result.is_ok(),
                "expected OK [{label}], got {:?}",
                result
                    .as_ref()
                    .err()
                    .map(|e| (e.errcode.clone(), e.error.clone()))
            );
        } else {
            let err = result.expect_err(&format!("expected error [{label}]"));
            assert_eq!(
                err.errcode,
                exp["errcode"].as_str().unwrap(),
                "errcode [{label}]"
            );
            assert_eq!(
                err.error,
                exp["error"].as_str().unwrap(),
                "error message [{label}]"
            );
        }
    }
}

#[test]
fn resolve_state_parity() {
    let d = load();
    for case in d["resolveState"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap_or("?");
        let room_version = case.get("roomVersion").and_then(Value::as_str);
        let forks: Vec<StateEvents> = case["stateAtForks"]
            .as_array()
            .unwrap()
            .iter()
            .map(state_events_from)
            .collect();
        let auth_events: HashMap<String, Value> = case["authEvents"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        let room = room_from(&case["roomState"]);

        let resolved = resolve_state(&forks, &auth_events, &room, room_version);
        let expected = state_events_from(&case["resolved"]);
        assert_eq!(resolved, expected, "resolved state mismatch [{label}]");
    }
}
