//! Byte-parity tests for the Phase-1 crypto/canonical-JSON/event core.
//!
//! Every expected value in `fixtures/phase1.json` is the actual output of
//! strix's real TypeScript functions (generated by `fixtures/gen-phase1.mjs`).
//! These tests assert scandiaca reproduces them exactly — the foundation of
//! federation interop.

use base64::engine::general_purpose::STANDARD;
use base64::Engine;
use scandiaca::canonical_json::canonical_json;
use scandiaca::events::{
    compute_content_hash, compute_event_id, compute_room_id_v12, redact_event,
};
use scandiaca::signing::{derive_key_id, import_signing_key, sign_event, sign_json, SigningKey};
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/phase1.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("phase1.json must be valid JSON")
}

/// The deterministic test key used by the generator: seed = 32 × 0x01.
fn test_key() -> SigningKey {
    import_signing_key("ed25519:test", [1u8; 32])
}

#[test]
fn canonical_json_parity() {
    let d = fixture();
    let cases = d["canonicalJson"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let input = &case["input"];
        let expected = case["output"].as_str().unwrap();
        assert_eq!(
            canonical_json(input),
            expected,
            "canonicalJson mismatch for input {input}"
        );
    }
}

#[test]
fn signing_key_parity() {
    let d = fixture();
    let sk = &d["signingKey"];

    // The fixture's base64 seed must decode to the 32×0x01 seed we use.
    let seed_vec = STANDARD.decode(sk["seedBase64"].as_str().unwrap()).unwrap();
    let seed: [u8; 32] = seed_vec.try_into().unwrap();
    assert_eq!(seed, [1u8; 32]);

    let key = import_signing_key("ed25519:test", seed);
    assert_eq!(
        key.public_key_base64,
        sk["publicKeyBase64"].as_str().unwrap()
    );
    assert_eq!(
        derive_key_id(&key.verifying),
        sk["alsoDerivedKeyId"].as_str().unwrap()
    );
}

#[test]
fn sign_json_parity() {
    let d = fixture();
    let key = test_key();
    for case in d["signJson"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap_or("?");
        let server = case["serverName"].as_str().unwrap();
        let key_id = case["keyId"].as_str().unwrap();

        let signed = sign_json(&case["input"], server, &key);
        let sig = signed["signatures"][server][key_id].as_str().unwrap();
        assert_eq!(
            sig,
            case["signatureBase64"].as_str().unwrap(),
            "signJson signature mismatch [{label}]"
        );
        assert_eq!(
            signed, case["signedObject"],
            "signJson signedObject mismatch [{label}]"
        );
    }
}

#[test]
fn events_parity() {
    let d = fixture();
    for case in d["events"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap_or("?");
        let rv = case["roomVersion"].as_str();
        let pdu = &case["pdu"];

        assert_eq!(
            redact_event(pdu, rv),
            case["redacted"],
            "redact mismatch [{label}]"
        );
        assert_eq!(
            compute_content_hash(pdu),
            case["contentHash"].as_str().unwrap(),
            "contentHash mismatch [{label}]"
        );
        assert_eq!(
            compute_event_id(pdu, rv),
            case["eventId"].as_str().unwrap(),
            "eventId mismatch [{label}]"
        );
        if let Some(room_id) = case.get("roomIdV12").and_then(Value::as_str) {
            assert_eq!(
                compute_room_id_v12(pdu),
                room_id,
                "roomIdV12 mismatch [{label}]"
            );
        }
    }
}

#[test]
fn sign_event_parity() {
    let d = fixture();
    let key = test_key();
    for case in d["signEvent"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap_or("?");
        let rv = case["roomVersion"].as_str();

        let signed = sign_event(&case["pdu"], "test.localhost", &key, rv);
        let sig = signed["signatures"]["test.localhost"]["ed25519:test"]
            .as_str()
            .unwrap();
        assert_eq!(
            sig,
            case["signatureBase64"].as_str().unwrap(),
            "signEvent signature mismatch [{label}]"
        );
        assert_eq!(
            signed, case["signedEvent"],
            "signEvent signedEvent mismatch [{label}]"
        );
    }
}
